/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dmlc_mxnet_Predictor */

#ifndef _Included_org_dmlc_mxnet_PredictorEncrypt
#define _Included_org_dmlc_mxnet_PredictorEncrypt
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_jniInit
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
JNIEXPORT jint JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_jniInit_backup
  (JNIEnv *, jclass, jobject, jstring, jstring);
*/

/*
JNIEXPORT jint JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_checkValidation
  (JNIEnv *, jclass, jstring, jstring);
*/

JNIEXPORT jint JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_decodeNN
  (JNIEnv *, jclass, jbyteArray, jbyteArray);


JNIEXPORT jlong JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_createPredictor
  (JNIEnv *, jclass, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     org_dmlc_mxnet_Predictor
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_dmlc_mxnet_Predictor
 * Method:    nativeGetOutput
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_nativeGetOutput
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_dmlc_mxnet_Predictor
 * Method:    nativeForward
 * Signature: (JLjava/lang/String;[F)V
 */

JNIEXPORT void JNICALL Java_org_dmlc_mxnet_PredictorEncrypt_nativeForward
  (JNIEnv *, jclass, jlong, jstring, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
